export const paymentsData = [
  {
    id: "KZ2Gs2uA",
    orderId: "my_order_id",
    amount: 45,
    amountRefunded: 45,
    date: "2021-12-02T12:52:22.585194+00:00",
    status: "SETTLED",
    processor: "STRIPE",
    paymentInstrument: {
      token: "27wGIYl5RN6BtrZyMi67_HwxNjM4NDQ5NTQw",
      analyticsId: "OLNeV0cOWB-ngqb5p3R6SjNR",
      tokenType: "SINGLE_USE",
      paymentInstrumentType: "PAYMENT_CARD",
      paymentInstrumentData: {
        last4Digits: "4242",
        first6Digits: "424242",
        expirationMonth: "03",
        expirationYear: "2030",
        cardholderName: "John Doe",
        network: "Visa",
        isNetworkTokenized: false,
        binData: {
          network: "VISA",
          issuerCountryCode: "US",
          issuerName: null,
          issuerCurrencyCode: null,
          regionalRestriction: "UNKNOWN",
          accountNumberType: "UNKNOWN",
          accountFundingType: "UNKNOWN",
          prepaidReloadableIndicator: "NOT_APPLICABLE",
          productUsageType: "UNKNOWN",
          productCode: "VISA",
          productName: "VISA",
        },
      },
      threeDSecureAuthentication: {
        responseCode: "NOT_PERFORMED",
        reasonCode: null,
        reasonText: null,
        protocolVersion: null,
        challengeIssued: null,
      },
    },
    currencyCode: "EUR",
    processorMerchantId: "acct_1GORcsGZqNWFwi8c",
  },
  {
    id: "6XcFS4uV",
    orderId: "WsEqBrTZvVLrUZYXrVsD",
    amount: 1000,
    amountRefunded: 0,
    date: "2020-12-08T14:34:29.253182+00:00",
    status: "FAILED",
    processor: "PAYPAL",
    paymentInstrument: {
      token: "Nd4X1h4pSr2hIEPzwulE3XwxNjA3NDM4MDY4",
      analyticsId: "LF0wHNjLXJSibsryKdOp8Gwt",
      tokenType: "SINGLE_USE",
      paymentInstrumentType: "PAYPAL_ORDER",
      paymentInstrumentData: {
        paypalOrderId: "QUFBjkRVWcEwCjEIHseshAWyDqHFYPvq",
        externalPayerInfo: null,
        paypalStatus: null,
      },
      threeDSecureAuthentication: {
        responseCode: "NOT_PERFORMED",
        reasonCode: null,
        reasonText: null,
        protocolVersion: null,
        challengeIssued: null,
      },
    },
    currencyCode: "GBP",
    processorMerchantId: "sb-32arh1340866@business.example.com",
  },
  {
    id: "1TKha2s1",
    orderId: "CFqNgojUMqHRGzlOFVBJDX",
    amount: 199,
    amountRefunded: 0,
    date: "2020-12-08T14:34:24.374751+00:00",
    status: "SETTLING",
    processor: "ADYEN",
    paymentInstrument: {
      token: "Qy1Nq08xToS8nODRncjIvnwxNjA3NDM4MDYz",
      analyticsId: "J6HhBcMmWgWy5lUaYfffe2oz",
      tokenType: "SINGLE_USE",
      paymentInstrumentType: "PAYMENT_CARD",
      paymentInstrumentData: {
        last4Digits: "1111",
        first6Digits: null,
        expirationMonth: "03",
        expirationYear: "2030",
        cardholderName: "MR F. Bar",
        network: "Visa",
        isNetworkTokenized: false,
        binData: {
          network: "VISA",
          issuerCountryCode: null,
          issuerName: null,
          issuerCurrencyCode: null,
          regionalRestriction: "UNKNOWN",
          accountNumberType: "UNKNOWN",
          accountFundingType: "UNKNOWN",
          prepaidReloadableIndicator: "NOT_APPLICABLE",
          productUsageType: "UNKNOWN",
          productCode: "VISA",
          productName: "VISA",
        },
      },
      threeDSecureAuthentication: null,
    },
    currencyCode: "EUR",
    processorMerchantId: "PrimerJbTestECOM",
  },
  {
    id: "ORzm8dBi",
    orderId: "nVpDsoYhQhzKlaiBpgjrqe",
    amount: 2000,
    amountRefunded: 0,
    date: "2020-12-08T14:34:20.635258+00:00",
    status: "SETTLING",
    processor: "ADYEN",
    paymentInstrument: {
      token: "kPKn4fgvQBmYA3Z8BJOhA3wxNjA3NDM4MDYw",
      analyticsId: "uEwN0OKdVWi0btoc4cI9uFBk",
      tokenType: "SINGLE_USE",
      paymentInstrumentType: "PAYMENT_CARD",
      paymentInstrumentData: {
        last4Digits: "0004",
        first6Digits: null,
        expirationMonth: "03",
        expirationYear: "2030",
        cardholderName: "Mrs Fred Bazzington",
        network: "other",
        isNetworkTokenized: false,
        binData: {
          network: "MAESTRO",
          issuerCountryCode: null,
          issuerName: null,
          issuerCurrencyCode: null,
          regionalRestriction: "UNKNOWN",
          accountNumberType: "UNKNOWN",
          accountFundingType: "UNKNOWN",
          prepaidReloadableIndicator: "NOT_APPLICABLE",
          productUsageType: "UNKNOWN",
          productCode: "MAESTRO",
          productName: "MAESTRO",
        },
      },
      threeDSecureAuthentication: null,
    },
    currencyCode: "EUR",
    processorMerchantId: "PrimerJbTestECOM",
  },
  {
    id: "C0wQApvC",
    orderId: "tmnOGVggEgxQWhkLwzNzvk",
    amount: 394,
    amountRefunded: 0,
    date: "2020-12-08T14:34:16.906517+00:00",
    status: "SETTLING",
    processor: "ADYEN",
    paymentInstrument: {
      token: "GSjjhXwKQ-iMj5GKOeKEhnwxNjA3NDM4MDU2",
      analyticsId: "uEwN0OKdVWi0btoc4cI9uFBk",
      tokenType: "SINGLE_USE",
      paymentInstrumentType: "PAYMENT_CARD",
      paymentInstrumentData: {
        last4Digits: "0004",
        first6Digits: null,
        expirationMonth: "03",
        expirationYear: "2030",
        cardholderName: "F. B. BAZ ESQ",
        network: "other",
        isNetworkTokenized: false,
        binData: {
          network: "MAESTRO",
          issuerCountryCode: null,
          issuerName: null,
          issuerCurrencyCode: null,
          regionalRestriction: "UNKNOWN",
          accountNumberType: "UNKNOWN",
          accountFundingType: "UNKNOWN",
          prepaidReloadableIndicator: "NOT_APPLICABLE",
          productUsageType: "UNKNOWN",
          productCode: "MAESTRO",
          productName: "MAESTRO",
        },
      },
      threeDSecureAuthentication: null,
    },
    currencyCode: "EUR",
    processorMerchantId: "PrimerJbTestECOM",
  },
  {
    id: "xQCAIj6z",
    orderId: "yccQHZoZhFYkWbyPgODEih",
    amount: 100000,
    amountRefunded: 0,
    date: "2020-12-08T14:34:13.207836+00:00",
    status: "SETTLING",
    processor: "ADYEN",
    paymentInstrument: {
      token: "CaBu6Gr5TQmMHdRUZJkL43wxNjA3NDM4MDUy",
      analyticsId: "0aRlD7pxWemZECJj96kTy0ls",
      tokenType: "SINGLE_USE",
      paymentInstrumentType: "PAYMENT_CARD",
      paymentInstrumentData: {
        last4Digits: "4444",
        first6Digits: null,
        expirationMonth: "03",
        expirationYear: "2030",
        cardholderName: "MR F. B. BAZ",
        network: "Mastercard",
        isNetworkTokenized: false,
        binData: {
          network: "MASTERCARD",
          issuerCountryCode: null,
          issuerName: null,
          issuerCurrencyCode: null,
          regionalRestriction: "UNKNOWN",
          accountNumberType: "UNKNOWN",
          accountFundingType: "UNKNOWN",
          prepaidReloadableIndicator: "NOT_APPLICABLE",
          productUsageType: "UNKNOWN",
          productCode: "MASTERCARD",
          productName: "MASTERCARD",
        },
      },
      threeDSecureAuthentication: null,
    },
    currencyCode: "EUR",
    processorMerchantId: "PrimerJbTestECOM",
  },
  {
    id: "medWBCt2",
    orderId: "okaMIBOluwwqMuEwtpuMNV",
    amount: 599,
    amountRefunded: 0,
    date: "2020-12-08T14:34:09.574595+00:00",
    status: "SETTLING",
    processor: "ADYEN",
    paymentInstrument: {
      token: "i1v_5i7yTLuFWUKsOZZCTXwxNjA3NDM4MDQ5",
      analyticsId: "J6HhBcMmWgWy5lUaYfffe2oz",
      tokenType: "SINGLE_USE",
      paymentInstrumentType: "PAYMENT_CARD",
      paymentInstrumentData: {
        last4Digits: "1111",
        first6Digits: null,
        expirationMonth: "03",
        expirationYear: "2030",
        cardholderName: "MR FOO BAR",
        network: "Visa",
        isNetworkTokenized: false,
        binData: {
          network: "VISA",
          issuerCountryCode: null,
          issuerName: null,
          issuerCurrencyCode: null,
          regionalRestriction: "UNKNOWN",
          accountNumberType: "UNKNOWN",
          accountFundingType: "UNKNOWN",
          prepaidReloadableIndicator: "NOT_APPLICABLE",
          productUsageType: "UNKNOWN",
          productCode: "VISA",
          productName: "VISA",
        },
      },
      threeDSecureAuthentication: null,
    },
    currencyCode: "EUR",
    processorMerchantId: "PrimerJbTestECOM",
  },
  {
    id: "sIZipdl7",
    orderId: "oMspVVlskaXkaZOTEfZSEe",
    amount: 2000,
    amountRefunded: 0,
    date: "2020-12-08T14:34:07.318826+00:00",
    status: "AUTHORIZED",
    processor: "ADYEN",
    paymentInstrument: {
      token: "Js6ZL77VQZSdagXlfvaSuXwxNjA3NDM4MDQ2",
      analyticsId: "uEwN0OKdVWi0btoc4cI9uFBk",
      tokenType: "SINGLE_USE",
      paymentInstrumentType: "PAYMENT_CARD",
      paymentInstrumentData: {
        last4Digits: "0004",
        first6Digits: null,
        expirationMonth: "03",
        expirationYear: "2030",
        cardholderName: "Mrs Fred Bazzington",
        network: "other",
        isNetworkTokenized: false,
        binData: {
          network: "MAESTRO",
          issuerCountryCode: null,
          issuerName: null,
          issuerCurrencyCode: null,
          regionalRestriction: "UNKNOWN",
          accountNumberType: "UNKNOWN",
          accountFundingType: "UNKNOWN",
          prepaidReloadableIndicator: "NOT_APPLICABLE",
          productUsageType: "UNKNOWN",
          productCode: "MAESTRO",
          productName: "MAESTRO",
        },
      },
      threeDSecureAuthentication: null,
    },
    currencyCode: "EUR",
    processorMerchantId: "PrimerJbTestECOM",
  },
  {
    id: "RDIpOeHM",
    orderId: "GEbThuXOGzIrCDtDilPtmZ",
    amount: 394,
    amountRefunded: 0,
    date: "2020-12-08T14:34:04.976225+00:00",
    status: "AUTHORIZED",
    processor: "ADYEN",
    paymentInstrument: {
      token: "g4LAIDeEQ3KybCBOp6n3UXwxNjA3NDM4MDQ0",
      analyticsId: "uEwN0OKdVWi0btoc4cI9uFBk",
      tokenType: "SINGLE_USE",
      paymentInstrumentType: "PAYMENT_CARD",
      paymentInstrumentData: {
        last4Digits: "0004",
        first6Digits: null,
        expirationMonth: "03",
        expirationYear: "2030",
        cardholderName: "F. B. BAZ ESQ",
        network: "other",
        isNetworkTokenized: false,
        binData: {
          network: "MAESTRO",
          issuerCountryCode: null,
          issuerName: null,
          issuerCurrencyCode: null,
          regionalRestriction: "UNKNOWN",
          accountNumberType: "UNKNOWN",
          accountFundingType: "UNKNOWN",
          prepaidReloadableIndicator: "NOT_APPLICABLE",
          productUsageType: "UNKNOWN",
          productCode: "MAESTRO",
          productName: "MAESTRO",
        },
      },
      threeDSecureAuthentication: null,
    },
    currencyCode: "EUR",
    processorMerchantId: "PrimerJbTestECOM",
  },
];
export const paymentDetails = [
  {},
  {
    transactions: [
      {
        id: "7fb48e7e-a1ce-45f6-b034-392a71cd69f7",
        processorTransactionId: null,
        processor: "PAYPAL",
        processorMerchantId: "sb-32arh1340866@business.example.com",
        type: "SALE",
        status: "FAILED",
        paymentError: {
          date: "2020-12-08T14:34:30.234479",
          type: "APPLICATION_ERROR",
          declineCode: null,
          declineType: null,
          processorMessage: "The specified resource does not exist.",
        },
      },
    ],
  },
  {
    transactions: [
      {
        id: "78028b18-ac16-4436-ba9a-3528f409f305",
        processorTransactionId: "vOqSTvUdxLPKegc",
        processor: "ADYEN",
        processorMerchantId: "PrimerJbTestECOM",
        type: "SALE",
        status: "SETTLING",
        paymentError: null,
      },
      {
        id: "a0a4bbc8-49af-42dc-9c06-000e627b0fca",
        processorTransactionId: null,
        processor: "ADYEN",
        processorMerchantId: "PrimerJbTestECOM",
        type: "REFUND",
        status: "PENDING",
        paymentError: {
          date: "2020-12-08T14:34:27.779919",
          type: "APPLICATION_ERROR",
          declineCode: null,
          declineType: null,
          processorMessage: "Missing Authentication Token",
        },
      },
    ],
  },
  {
    transactions: [
      {
        id: "3719d225-fdeb-481f-8609-554f5862f932",
        processorTransactionId: "uptBdZhvRKSfpRp",
        processor: "ADYEN",
        processorMerchantId: "PrimerJbTestECOM",
        type: "SALE",
        status: "SETTLING",
        paymentError: null,
      },
    ],
  },
  {
    transactions: [
      {
        id: "613db7bc-968c-4852-a0d9-b74a09dca624",
        processorTransactionId: "kavyhgpOqieKetV",
        processor: "ADYEN",
        processorMerchantId: "PrimerJbTestECOM",
        type: "SALE",
        status: "SETTLING",
        paymentError: null,
      },
    ],
  },
  {
    transactions: [
      {
        id: "34d665bf-49a8-4f1f-9c69-2db5c11ffdce",
        processorTransactionId: "DLNnajTfcmuUhzK",
        processor: "ADYEN",
        processorMerchantId: "PrimerJbTestECOM",
        type: "SALE",
        status: "SETTLING",
        paymentError: null,
      },
    ],
  },
  {
    transactions: [
      {
        id: "c292eb3b-4e43-44be-923c-8b4a0270c448",
        processorTransactionId: "hABpeVxKNjFThSu",
        processor: "ADYEN",
        processorMerchantId: "PrimerJbTestECOM",
        type: "SALE",
        status: "SETTLING",
        paymentError: null,
      },
    ],
  },
  {
    transactions: [
      {
        id: "ec2b0391-9266-4997-87f2-4dd2f492fc1e",
        processorTransactionId: "kBOKTBalrsVJqpr",
        processor: "ADYEN",
        processorMerchantId: "PrimerJbTestECOM",
        type: "SALE",
        status: "AUTHORIZED",
        paymentError: null,
      },
    ],
  },
  {
    transactions: [
      {
        id: "52e5134e-b218-45e4-ae4c-516c08234666",
        processorTransactionId: "HSqmKTOeAjihrZG",
        processor: "ADYEN",
        processorMerchantId: "PrimerJbTestECOM",
        type: "SALE",
        status: "AUTHORIZED",
        paymentError: null,
      },
    ],
  },
];
